# Generated by Project Ops Radar.

set dotenv-load := false

default:
    @just --list

status:
    git status --short --branch

install:
    @if [ -f package.json ]; then \
      if command -v pnpm >/dev/null 2>&1; then pnpm install; else npm install; fi; \
    elif [ -f app/package.json ]; then \
      cd app && if command -v pnpm >/dev/null 2>&1; then pnpm install; else npm install; fi; \
    else \
      echo "No package.json found."; \
    fi

build:
    @if [ -f package.json ]; then \
      if command -v pnpm >/dev/null 2>&1; then pnpm build; else npm run build; fi; \
    elif [ -f app/package.json ]; then \
      cd app && if command -v pnpm >/dev/null 2>&1; then pnpm build; else npm run build; fi; \
    else \
      echo "No build command configured."; \
    fi

test:
    @if [ -f package.json ]; then \
      if command -v pnpm >/dev/null 2>&1; then pnpm test; else npm test; fi; \
    elif [ -f app/package.json ]; then \
      cd app && if command -v pnpm >/dev/null 2>&1; then pnpm test; else npm test; fi; \
    else \
      echo "No test command configured."; \
    fi

lint:
    @if [ -f package.json ]; then \
      if command -v pnpm >/dev/null 2>&1; then pnpm lint; else npm run lint; fi; \
    elif [ -f app/package.json ]; then \
      cd app && if command -v pnpm >/dev/null 2>&1; then pnpm lint; else npm run lint; fi; \
    else \
      echo "No lint command configured."; \
    fi
