import type { SocialTarget } from "./social-funnel";

export type InitialSocialIdea = {
  externalId: string;
  pillar: string;
  format: string;
  hook: string;
  angle: string;
  target: SocialTarget;
  cta: string;
};

export const initialSocialIdeas: InitialSocialIdea[] = [
  {
    externalId: "mp-ig-001-prescricao-nao-e-burocracia",
    pillar: "regulacao",
    format: "carousel",
    hook: "Prescricao nao e burocracia. E filtro de seguranca.",
    angle: "Explicar por que peptideos exigem avaliacao profissional antes de qualquer orcamento.",
    target: "education",
    cta: "Entenda as regras",
  },
  {
    externalId: "mp-ig-002-semaglutida-vs-tirzepatida",
    pillar: "comparacao",
    format: "carousel",
    hook: "Semaglutida e tirzepatida nao sao a mesma conversa.",
    angle: "Comparar mecanismos em linguagem simples, sem sugerir troca ou escolha direta.",
    target: "education",
    cta: "Compare com calma",
  },
  {
    externalId: "mp-ig-003-orcamento-com-prescricao",
    pillar: "orcamento",
    format: "static",
    hook: "Tem prescricao? O proximo passo e pedir orcamento com criterio.",
    angle: "Direcionar pacientes com prescricao para pedido privado de cotacao.",
    target: "patient_quote",
    cta: "Solicitar orcamento",
  },
  {
    externalId: "mp-ig-004-sinais-de-promessa-arriscada",
    pillar: "compliance",
    format: "carousel",
    hook: "Quando a promessa parece facil demais, pare.",
    angle: "Listar sinais de alerta: sem receita, resultado garantido, antes/depois.",
    target: "education",
    cta: "Veja sinais de risco",
  },
  {
    externalId: "mp-ig-005-medico-parceiro",
    pillar: "medicos",
    format: "static",
    hook: "Medico: receba pacientes que ja chegam com pergunta estruturada.",
    angle: "Chamada B2B para cadastro discreto de medicos parceiros.",
    target: "doctor_signup",
    cta: "Cadastrar perfil",
  },
  {
    externalId: "mp-ig-006-farmacia-parceira",
    pillar: "farmacias",
    format: "static",
    hook: "Farmacia de manipulacao: existe demanda qualificada procurando resposta.",
    angle: "Chamada para farmacias entrarem na fila de parceria B2B.",
    target: "pharmacy_partner",
    cta: "Avaliar parceria",
  },
  {
    externalId: "mp-ig-007-o-que-e-peptideo",
    pillar: "educacao",
    format: "carousel",
    hook: "Peptideo nao e uma categoria unica.",
    angle: "Explicar diversidade de usos, evidencias e regulacao por composto.",
    target: "education",
    cta: "Aprenda o basico",
  },
  {
    externalId: "mp-ig-008-bpc157-na-internet",
    pillar: "evidencia",
    format: "carousel",
    hook: "BPC-157 viralizou. A evidencia ainda precisa ser lida com cuidado.",
    angle: "Separar fama online, pesquisa preliminar e decisao medica.",
    target: "education",
    cta: "Ver metodologia",
  },
  {
    externalId: "mp-ig-009-ghk-cu",
    pillar: "educacao",
    format: "carousel",
    hook: "GHK-Cu aparece no skincare, mas o contexto importa.",
    angle: "Diferenciar cosmetico, manipulacao e alegacoes sem base.",
    target: "education",
    cta: "Entenda o contexto",
  },
  {
    externalId: "mp-ig-010-checklist-prescricao",
    pillar: "orcamento",
    format: "carousel",
    hook: "Antes do orcamento, tenha estes dados em maos.",
    angle: "Checklist de prescricao, dosagem, apresentacao e cidade.",
    target: "patient_quote",
    cta: "Preparar pedido",
  },
  {
    externalId: "mp-ig-011-medico-sem-exposicao",
    pillar: "medicos",
    format: "carousel",
    hook: "Nem todo medico quer aparecer em diretorio publico.",
    angle: "Explicar cadastro medico privado e indicacao individual.",
    target: "doctor_signup",
    cta: "Entrar no cadastro",
  },
  {
    externalId: "mp-ig-012-farmacia-sem-vitrine",
    pillar: "farmacias",
    format: "carousel",
    hook: "Parceria B2B nao precisa virar vitrine publica.",
    angle: "Explicar roteamento privado de pedidos para farmacias revisadas.",
    target: "pharmacy_partner",
    cta: "Conhecer parceria",
  },
  {
    externalId: "mp-ig-013-anvisa-em-1-minuto",
    pillar: "regulacao",
    format: "reel",
    hook: "Anvisa em 1 minuto: o que muda para peptideos?",
    angle: "Resumo educativo com chamada para pagina de regulamentacao.",
    target: "education",
    cta: "Ver guia completo",
  },
  {
    externalId: "mp-ig-014-nao-compre-por-dm",
    pillar: "compliance",
    format: "static",
    hook: "Peptideo por DM nao e atalho. E risco.",
    angle: "Mensagem direta contra compra informal e sem prescricao.",
    target: "education",
    cta: "Entenda os riscos",
  },
  {
    externalId: "mp-ig-015-clinicas-locais",
    pillar: "clinicas",
    format: "static",
    hook: "Clinica: pacientes pesquisam antes de agendar.",
    angle: "Topo de funil para diretorio premium de clinicas.",
    target: "clinic_directory",
    cta: "Avaliar cidade",
  },
  {
    externalId: "mp-ig-016-pergunta-ao-medico",
    pillar: "educacao",
    format: "carousel",
    hook: "5 perguntas para levar ao medico antes de falar em peptideos.",
    angle: "Orientar conversa clinica sem recomendar tratamento.",
    target: "education",
    cta: "Salvar checklist",
  },
  {
    externalId: "mp-ig-017-dose-nao-e-conteudo",
    pillar: "compliance",
    format: "static",
    hook: "Dose nao e conteudo de Instagram.",
    angle: "Explicar por que dose depende de prescricao individual.",
    target: "education",
    cta: "Leia antes de decidir",
  },
  {
    externalId: "mp-ig-018-cidade-e-envio",
    pillar: "orcamento",
    format: "carousel",
    hook: "Sua cidade muda o caminho do orcamento.",
    angle: "Explicar match por UF, envio nacional e disponibilidade.",
    target: "patient_quote",
    cta: "Pedir orcamento",
  },
  {
    externalId: "mp-ig-019-evidencia-proven-research",
    pillar: "metodologia",
    format: "carousel",
    hook: "Provado, em pesquisa ou sem base? Nao trate tudo igual.",
    angle: "Explicar taxonomia editorial do site.",
    target: "education",
    cta: "Ver metodologia",
  },
  {
    externalId: "mp-ig-020-mapa-de-laboratorios",
    pillar: "farmacias",
    format: "carousel",
    hook: "Estamos mapeando farmacias serias por regiao.",
    angle: "Chamar farmacias para parceria e revisao de criterios.",
    target: "pharmacy_partner",
    cta: "Entrar no mapa",
  },
  {
    externalId: "mp-ig-021-caso-sem-nome",
    pillar: "educacao",
    format: "carousel",
    hook: "O caso real: muita informacao, pouca orientacao.",
    angle: "Narrativa anonima de jornada de pesquisa ate orientacao medica.",
    target: "education",
    cta: "Organize sua pesquisa",
  },
  {
    externalId: "mp-ig-022-o-que-farmacia-recebe",
    pillar: "farmacias",
    format: "static",
    hook: "O que uma farmacia parceira recebe?",
    angle: "Detalhar dados minimos do pedido: composto, cidade, contato e consentimento.",
    target: "pharmacy_partner",
    cta: "Ver parceria",
  },
  {
    externalId: "mp-ig-023-medico-lead-qualificado",
    pillar: "medicos",
    format: "carousel",
    hook: "Lead qualificado nao e contato frio.",
    angle: "Explicar interesse declarado, cidade e consentimento no fluxo medico.",
    target: "doctor_signup",
    cta: "Receber leads",
  },
  {
    externalId: "mp-ig-024-tirzepatida-em-contexto",
    pillar: "educacao",
    format: "carousel",
    hook: "Tirzepatida: contexto antes de conclusao.",
    angle: "Resumo com beneficio, risco e necessidade de avaliacao clinica.",
    target: "education",
    cta: "Ler resumo",
  },
  {
    externalId: "mp-ig-025-glp1-nao-e-estetica",
    pillar: "compliance",
    format: "static",
    hook: "GLP-1 nao deve ser reduzido a estetica.",
    angle: "Reforcar acompanhamento medico e indicacoes adequadas.",
    target: "education",
    cta: "Entenda melhor",
  },
  {
    externalId: "mp-ig-026-como-comparar-orcamentos",
    pillar: "orcamento",
    format: "carousel",
    hook: "Preco sozinho nao compara orcamento.",
    angle: "Listar apresentacao, concentracao, prazo, envio e atendimento.",
    target: "patient_quote",
    cta: "Solicitar com dados",
  },
  {
    externalId: "mp-ig-027-perfil-de-parceiro",
    pillar: "farmacias",
    format: "carousel",
    hook: "Que farmacia faz sentido para o Meus Peptideos?",
    angle: "Criterios: atendimento, reputacao, prescricao, logistica e transparencia.",
    target: "pharmacy_partner",
    cta: "Avaliar fit",
  },
  {
    externalId: "mp-ig-028-diretorio-premium",
    pillar: "clinicas",
    format: "carousel",
    hook: "Diretorio premium e demanda local, nao outdoor.",
    angle: "Explicar paginas por cidade/composto para clinicas.",
    target: "clinic_directory",
    cta: "Avaliar cidade",
  },
  {
    externalId: "mp-ig-029-mitos-em-3-camadas",
    pillar: "evidencia",
    format: "carousel",
    hook: "Todo mito tem tres camadas: promessa, evidencia e risco.",
    angle: "Framework para analisar claims virais de peptideos.",
    target: "education",
    cta: "Usar framework",
  },
  {
    externalId: "mp-ig-030-roteamento-com-consentimento",
    pillar: "privacidade",
    format: "static",
    hook: "Seu contato so deve ir para parceiro com consentimento.",
    angle: "Explicar LGPD no roteamento para medico ou farmacia.",
    target: "education",
    cta: "Ver politica",
  },
];
