import type { SocialTarget } from "./social-funnel";

export type InitialSocialIdea = {
  externalId: string;
  pillar: string;
  format: string;
  hook: string;
  angle: string;
  target: SocialTarget;
  cta: string;
};

export const initialSocialIdeas: InitialSocialIdea[] = [
  {
    externalId: "mp-ig-001-prescricao-nao-e-burocracia",
    pillar: "regulacao",
    format: "carousel",
    hook: "Prescrição não é burocracia. É filtro de segurança.",
    angle: "Explicar por que peptídeos exigem avaliação profissional antes de qualquer orçamento.",
    target: "education",
    cta: "Entenda as regras",
  },
  {
    externalId: "mp-ig-002-semaglutida-vs-tirzepatida",
    pillar: "comparacao",
    format: "carousel",
    hook: "Semaglutida e tirzepatida não são a mesma conversa.",
    angle: "Comparar mecanismos em linguagem simples, sem sugerir troca ou escolha direta.",
    target: "education",
    cta: "Compare com calma",
  },
  {
    externalId: "mp-ig-003-orcamento-com-prescricao",
    pillar: "orçamento",
    format: "static",
    hook: "Tem prescrição? O próximo passo é pedir orçamento com critério.",
    angle: "Direcionar pacientes com prescrição para pedido privado de cotação.",
    target: "patient_quote",
    cta: "Solicitar orçamento",
  },
  {
    externalId: "mp-ig-004-sinais-de-promessa-arriscada",
    pillar: "compliance",
    format: "carousel",
    hook: "Quando a promessa parece facil demais, pare.",
    angle: "Listar sinais de alerta: sem receita, resultado garantido, antes/depois.",
    target: "education",
    cta: "Veja sinais de risco",
  },
  {
    externalId: "mp-ig-005-medico-parceiro",
    pillar: "médicos",
    format: "static",
    hook: "Médico: receba pacientes que já chegam com pergunta estruturada.",
    angle: "Chamada B2B para cadastro discreto de médicos parceiros.",
    target: "doctor_signup",
    cta: "Cadastrar perfil",
  },
  {
    externalId: "mp-ig-006-farmacia-parceira",
    pillar: "farmácias",
    format: "static",
    hook: "Farmácia de manipulação: existe demanda qualificada procurando resposta.",
    angle: "Chamada para farmácias entrarem na fila de parceria B2B.",
    target: "pharmacy_partner",
    cta: "Avaliar parceria",
  },
  {
    externalId: "mp-ig-007-o-que-e-peptideo",
    pillar: "educacao",
    format: "carousel",
    hook: "Peptídeo não é uma categoria única.",
    angle: "Explicar diversidade de usos, evidências e regulação por composto.",
    target: "education",
    cta: "Aprenda o basico",
  },
  {
    externalId: "mp-ig-008-bpc157-na-internet",
    pillar: "evidência",
    format: "carousel",
    hook: "BPC-157 viralizou. A evidência ainda precisa ser lida com cuidado.",
    angle: "Separar fama online, pesquisa preliminar e decisão médica.",
    target: "education",
    cta: "Ver metodologia",
  },
  {
    externalId: "mp-ig-009-ghk-cu",
    pillar: "educacao",
    format: "carousel",
    hook: "GHK-Cu aparece no skincare, mas o contexto importa.",
    angle: "Diferenciar cosmético, manipulação e alegações sem base.",
    target: "education",
    cta: "Entenda o contexto",
  },
  {
    externalId: "mp-ig-010-checklist-prescricao",
    pillar: "orçamento",
    format: "carousel",
    hook: "Antes do orçamento, tenha estes dados em mãos.",
    angle: "Checklist de prescrição, dosagem, apresentação e cidade.",
    target: "patient_quote",
    cta: "Preparar pedido",
  },
  {
    externalId: "mp-ig-011-medico-sem-exposicao",
    pillar: "médicos",
    format: "carousel",
    hook: "Nem todo médico quer aparecer em diretório público.",
    angle: "Explicar cadastro médico privado e indicação individual.",
    target: "doctor_signup",
    cta: "Entrar no cadastro",
  },
  {
    externalId: "mp-ig-012-farmacia-sem-vitrine",
    pillar: "farmácias",
    format: "carousel",
    hook: "Parceria B2B não precisa virar vitrine pública.",
    angle: "Explicar roteamento privado de pedidos para farmácias revisadas.",
    target: "pharmacy_partner",
    cta: "Conhecer parceria",
  },
  {
    externalId: "mp-ig-013-anvisa-em-1-minuto",
    pillar: "regulacao",
    format: "reel",
    hook: "Anvisa em 1 minuto: o que muda para peptídeos?",
    angle: "Resumo educativo com chamada para página de regulamentação.",
    target: "education",
    cta: "Ver guia completo",
  },
  {
    externalId: "mp-ig-014-nao-compre-por-dm",
    pillar: "compliance",
    format: "static",
    hook: "Peptídeo por DM não é atalho. É risco.",
    angle: "Mensagem direta contra compra informal e sem prescrição.",
    target: "education",
    cta: "Entenda os riscos",
  },
  {
    externalId: "mp-ig-015-clinicas-locais",
    pillar: "clínicas",
    format: "static",
    hook: "Clínica: pacientes pesquisam antes de agendar.",
    angle: "Topo de funil para diretório premium de clínicas.",
    target: "clinic_directory",
    cta: "Avaliar cidade",
  },
  {
    externalId: "mp-ig-016-pergunta-ao-medico",
    pillar: "educacao",
    format: "carousel",
    hook: "5 perguntas para levar ao médico antes de falar em peptídeos.",
    angle: "Orientar conversa clínica sem recomendar tratamento.",
    target: "education",
    cta: "Salvar checklist",
  },
  {
    externalId: "mp-ig-017-dose-nao-e-conteudo",
    pillar: "compliance",
    format: "static",
    hook: "Dose não é conteúdo de Instagram.",
    angle: "Explicar por que dose depende de prescrição individual.",
    target: "education",
    cta: "Leia antes de decidir",
  },
  {
    externalId: "mp-ig-018-cidade-e-envio",
    pillar: "orçamento",
    format: "carousel",
    hook: "Sua cidade muda o caminho do orçamento.",
    angle: "Explicar match por UF, envio nacional e disponibilidade.",
    target: "patient_quote",
    cta: "Pedir orçamento",
  },
  {
    externalId: "mp-ig-019-evidencia-proven-research",
    pillar: "metodologia",
    format: "carousel",
    hook: "Provado, em pesquisa ou sem base? Não trate tudo igual.",
    angle: "Explicar taxonomia editorial do site.",
    target: "education",
    cta: "Ver metodologia",
  },
  {
    externalId: "mp-ig-020-mapa-de-laboratorios",
    pillar: "farmácias",
    format: "carousel",
    hook: "Estamos mapeando farmácias sérias por região.",
    angle: "Chamar farmácias para parceria e revisão de critérios.",
    target: "pharmacy_partner",
    cta: "Entrar no mapa",
  },
  {
    externalId: "mp-ig-021-caso-sem-nome",
    pillar: "educacao",
    format: "carousel",
    hook: "O caso real: muita informacao, pouca orientacao.",
    angle: "Narrativa anônima de jornada de pesquisa até orientação médica.",
    target: "education",
    cta: "Organize sua pesquisa",
  },
  {
    externalId: "mp-ig-022-o-que-farmacia-recebe",
    pillar: "farmácias",
    format: "static",
    hook: "O que uma farmácia parceira recebe?",
    angle: "Detalhar dados minimos do pedido: composto, cidade, contato e consentimento.",
    target: "pharmacy_partner",
    cta: "Ver parceria",
  },
  {
    externalId: "mp-ig-023-medico-lead-qualificado",
    pillar: "médicos",
    format: "carousel",
    hook: "Lead qualificado não é contato frio.",
    angle: "Explicar interesse declarado, cidade e consentimento no fluxo médico.",
    target: "doctor_signup",
    cta: "Receber leads",
  },
  {
    externalId: "mp-ig-024-tirzepatida-em-contexto",
    pillar: "educacao",
    format: "carousel",
    hook: "Tirzepatida: contexto antes de conclusão.",
    angle: "Resumo com benefício, risco e necessidade de avaliação clínica.",
    target: "education",
    cta: "Ler resumo",
  },
  {
    externalId: "mp-ig-025-glp1-nao-e-estetica",
    pillar: "compliance",
    format: "static",
    hook: "GLP-1 não deve ser reduzido à estética.",
    angle: "Reforçar acompanhamento médico e indicações adequadas.",
    target: "education",
    cta: "Entenda melhor",
  },
  {
    externalId: "mp-ig-026-como-comparar-orcamentos",
    pillar: "orçamento",
    format: "carousel",
    hook: "Preço sozinho não compara orçamento.",
    angle: "Listar apresentação, concentração, prazo, envio e atendimento.",
    target: "patient_quote",
    cta: "Solicitar com dados",
  },
  {
    externalId: "mp-ig-027-perfil-de-parceiro",
    pillar: "farmácias",
    format: "carousel",
    hook: "Que farmácia faz sentido para o Meus Peptídeos?",
    angle: "Critérios: atendimento, reputação, prescrição, logística e transparência.",
    target: "pharmacy_partner",
    cta: "Avaliar fit",
  },
  {
    externalId: "mp-ig-028-diretorio-premium",
    pillar: "clínicas",
    format: "carousel",
    hook: "Diretório premium é demanda local, não outdoor.",
    angle: "Explicar páginas por cidade/composto para clínicas.",
    target: "clinic_directory",
    cta: "Avaliar cidade",
  },
  {
    externalId: "mp-ig-029-mitos-em-3-camadas",
    pillar: "evidência",
    format: "carousel",
    hook: "Todo mito tem três camadas: promessa, evidência e risco.",
    angle: "Framework para analisar claims virais de peptídeos.",
    target: "education",
    cta: "Usar framework",
  },
  {
    externalId: "mp-ig-030-roteamento-com-consentimento",
    pillar: "privacidade",
    format: "static",
    hook: "Seu contato so deve ir para parceiro com consentimento.",
    angle: "Explicar LGPD no roteamento para médico ou farmácia.",
    target: "education",
    cta: "Ver politica",
  },
];
