import type { SocialTarget } from "./social-funnel";

export type InitialSocialIdea = {
  externalId: string;
  pillar: string;
  format: string;
  hook: string;
  angle: string;
  target: SocialTarget;
  cta: string;
};

export const initialSocialIdeas: InitialSocialIdea[] = [
  {
    externalId: "mp-ig-001-prescricao-nao-e-burocracia",
    pillar: "regulacao",
    format: "carousel",
    hook: "Prescrição não é burocracia. É filtro de segurança.",
    angle: "Explicar por que peptídeos exigem avaliação profissional antes de qualquer orçamento.",
    target: "education",
    cta: "Entenda as regras",
  },
  {
    externalId: "mp-ig-002-semaglutida-vs-tirzepatida",
    pillar: "comparacao",
    format: "carousel",
    hook: "Semaglutida e tirzepatida não são a mesma conversa.",
    angle: "Comparar mecanismos em linguagem simples, sem sugerir troca ou escolha direta.",
    target: "education",
    cta: "Compare com calma",
  },
  {
    externalId: "mp-ig-003-orcamento-com-prescricao",
    pillar: "regulação",
    format: "static",
    hook: "Prescrição, registro e evidência são perguntas diferentes.",
    angle: "Explicar como verificar cada camada sem indicar compra ou tratamento.",
    target: "radar",
    cta: "Acompanhar mudanças",
  },
  {
    externalId: "mp-ig-004-sinais-de-promessa-arriscada",
    pillar: "compliance",
    format: "carousel",
    hook: "Quando a promessa parece facil demais, pare.",
    angle: "Listar sinais de alerta: sem receita, resultado garantido, antes/depois.",
    target: "education",
    cta: "Veja sinais de risco",
  },
  {
    externalId: "mp-ig-005-medico-parceiro",
    pillar: "profissionais",
    format: "static",
    hook: "Profissional de saúde: acompanhe o setor sem depender de post viral.",
    angle: "Apresentar o Radar profissional com estudos e fontes regulatórias.",
    target: "radar",
    cta: "Participar do piloto",
  },
  {
    externalId: "mp-ig-006-farmacia-parceira",
    pillar: "farmácias",
    format: "static",
    hook: "Farmácia: quais mudanças do setor merecem monitoramento semanal?",
    angle: "Validar o Radar B2B de evidências, regulação e interesse agregado.",
    target: "radar",
    cta: "Validar o Radar",
  },
  {
    externalId: "mp-ig-007-o-que-e-peptideo",
    pillar: "educacao",
    format: "carousel",
    hook: "Peptídeo não é uma categoria única.",
    angle: "Explicar diversidade de usos, evidências e regulação por composto.",
    target: "education",
    cta: "Aprenda o basico",
  },
  {
    externalId: "mp-ig-008-bpc157-na-internet",
    pillar: "evidência",
    format: "carousel",
    hook: "BPC-157 viralizou. A evidência ainda precisa ser lida com cuidado.",
    angle: "Separar fama online, pesquisa preliminar e decisão médica.",
    target: "education",
    cta: "Ver metodologia",
  },
  {
    externalId: "mp-ig-009-ghk-cu",
    pillar: "educacao",
    format: "carousel",
    hook: "GHK-Cu aparece no skincare, mas o contexto importa.",
    angle: "Diferenciar cosmético, manipulação e alegações sem base.",
    target: "education",
    cta: "Entenda o contexto",
  },
  {
    externalId: "mp-ig-010-checklist-prescricao",
    pillar: "educação",
    format: "carousel",
    hook: "Antes de confiar em um post, verifique estes cinco pontos.",
    angle: "Checklist de fonte, estágio de pesquisa, indicação, registro e data.",
    target: "radar",
    cta: "Receber o checklist",
  },
  {
    externalId: "mp-ig-011-medico-sem-exposicao",
    pillar: "profissionais",
    format: "carousel",
    hook: "O que um briefing regulatório precisa ter para ser útil?",
    angle: "Convidar profissionais a definir frequência, fontes e profundidade do Radar.",
    target: "radar",
    cta: "Opinar no piloto",
  },
  {
    externalId: "mp-ig-012-farmacia-sem-vitrine",
    pillar: "farmácias",
    format: "carousel",
    hook: "Dados agregados ajudam a planejar sem expor pacientes.",
    angle: "Explicar como o Radar separa inteligência de mercado de dados pessoais.",
    target: "radar",
    cta: "Conhecer o Radar B2B",
  },
  {
    externalId: "mp-ig-013-anvisa-em-1-minuto",
    pillar: "regulacao",
    format: "reel",
    hook: "Anvisa em 1 minuto: o que muda para peptídeos?",
    angle: "Resumo educativo com chamada para página de regulamentação.",
    target: "education",
    cta: "Ver guia completo",
  },
  {
    externalId: "mp-ig-014-nao-compre-por-dm",
    pillar: "compliance",
    format: "static",
    hook: "Peptídeo por DM não é atalho. É risco.",
    angle: "Mensagem direta contra compra informal e sem prescrição.",
    target: "education",
    cta: "Entenda os riscos",
  },
  {
    externalId: "mp-ig-015-clinicas-locais",
    pillar: "clínicas",
    format: "static",
    hook: "Clínica: quais dúvidas estão crescendo antes de chegarem ao consultório?",
    angle: "Validar relatórios agregados de interesse editorial para planejamento.",
    target: "radar",
    cta: "Participar do piloto",
  },
  {
    externalId: "mp-ig-016-pergunta-ao-medico",
    pillar: "educacao",
    format: "carousel",
    hook: "5 perguntas para levar ao médico antes de falar em peptídeos.",
    angle: "Orientar conversa clínica sem recomendar tratamento.",
    target: "education",
    cta: "Salvar checklist",
  },
  {
    externalId: "mp-ig-017-dose-nao-e-conteudo",
    pillar: "compliance",
    format: "static",
    hook: "Dose não é conteúdo de Instagram.",
    angle: "Explicar por que dose depende de prescrição individual.",
    target: "education",
    cta: "Leia antes de decidir",
  },
  {
    externalId: "mp-ig-018-cidade-e-envio",
    pillar: "mercado",
    format: "carousel",
    hook: "Interesse por peptídeos não cresce igual em todas as regiões.",
    angle: "Apresentar a hipótese de sinais regionais agregados, sem identificar pessoas.",
    target: "radar",
    cta: "Validar esse relatório",
  },
  {
    externalId: "mp-ig-019-evidencia-proven-research",
    pillar: "metodologia",
    format: "carousel",
    hook: "Provado, em pesquisa ou sem base? Não trate tudo igual.",
    angle: "Explicar taxonomia editorial do site.",
    target: "education",
    cta: "Ver metodologia",
  },
  {
    externalId: "mp-ig-020-mapa-de-laboratorios",
    pillar: "farmácias",
    format: "carousel",
    hook: "Como mapear o setor sem transformar lista em recomendação?",
    angle: "Mostrar critérios de dados públicos, atualização e direito de correção.",
    target: "radar",
    cta: "Acompanhar a metodologia",
  },
  {
    externalId: "mp-ig-021-caso-sem-nome",
    pillar: "educacao",
    format: "carousel",
    hook: "O caso real: muita informacao, pouca orientacao.",
    angle: "Narrativa anônima de jornada de pesquisa até orientação médica.",
    target: "education",
    cta: "Organize sua pesquisa",
  },
  {
    externalId: "mp-ig-022-o-que-farmacia-recebe",
    pillar: "farmácias",
    format: "static",
    hook: "O que entra em um relatório de mercado responsável?",
    angle: "Detalhar indicadores agregados, fontes e limites de interpretação.",
    target: "radar",
    cta: "Ver o Radar",
  },
  {
    externalId: "mp-ig-023-medico-lead-qualificado",
    pillar: "profissionais",
    format: "carousel",
    hook: "O estudo saiu. O que realmente mudou na prática?",
    angle: "Mostrar o formato do briefing profissional sem extrapolar resultados.",
    target: "radar",
    cta: "Testar o Radar",
  },
  {
    externalId: "mp-ig-024-tirzepatida-em-contexto",
    pillar: "educacao",
    format: "carousel",
    hook: "Tirzepatida: contexto antes de conclusão.",
    angle: "Resumo com benefício, risco e necessidade de avaliação clínica.",
    target: "education",
    cta: "Ler resumo",
  },
  {
    externalId: "mp-ig-025-glp1-nao-e-estetica",
    pillar: "compliance",
    format: "static",
    hook: "GLP-1 não deve ser reduzido à estética.",
    angle: "Reforçar acompanhamento médico e indicações adequadas.",
    target: "education",
    cta: "Entenda melhor",
  },
  {
    externalId: "mp-ig-026-como-comparar-orcamentos",
    pillar: "evidência",
    format: "carousel",
    hook: "Número grande sozinho não resume um estudo.",
    angle: "Ensinar a comparar amostra, duração, desfecho e população estudada.",
    target: "radar",
    cta: "Receber análises",
  },
  {
    externalId: "mp-ig-027-perfil-de-parceiro",
    pillar: "farmácias",
    format: "carousel",
    hook: "Quais sinais regulatórios uma equipe de compliance precisa acompanhar?",
    angle: "Validar alertas por substância, agência e impacto operacional.",
    target: "radar",
    cta: "Definir o piloto",
  },
  {
    externalId: "mp-ig-028-diretorio-premium",
    pillar: "clínicas",
    format: "carousel",
    hook: "Conteúdo clínico responsável começa pelos limites da evidência.",
    angle: "Apresentar briefing editorial para equipes de clínicas.",
    target: "radar",
    cta: "Conhecer o Radar",
  },
  {
    externalId: "mp-ig-029-mitos-em-3-camadas",
    pillar: "evidência",
    format: "carousel",
    hook: "Todo mito tem três camadas: promessa, evidência e risco.",
    angle: "Framework para analisar claims virais de peptídeos.",
    target: "education",
    cta: "Usar framework",
  },
  {
    externalId: "mp-ig-030-roteamento-com-consentimento",
    pillar: "privacidade",
    format: "static",
    hook: "Seu contato só deve ser usado para a finalidade que você autorizou.",
    angle: "Explicar consentimento, double opt-in e cancelamento no Radar.",
    target: "education",
    cta: "Ver política",
  },
];
